# Generated by Django 4.2.14 on 2024-07-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Categorie",
        ),
        migrations.RenameModel(
            old_name="Icons",
            new_name="Icon",
        ),
    ]
