# Generated by Django 4.2.14 on 2024-07-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_rename_categories_categorie_rename_icons_icon"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categorie",
            new_name="Category",
        ),
    ]
