# Generated by Django 4.2.7 on 2024-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_rename_author_tool_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
