# Generated by Django 4.2.7 on 2024-07-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0005_tool_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tool",
            old_name="user",
            new_name="owner",
        ),
    ]
